### ISSUE TITLE
[BUG] Mod not loading on 1.15.2

### ISSUE THREAD

**Issue by vizthex123** [xhayper/oldcombatsystem#4]
**MC Version:** 1.15.2

**Mod Version:** 2.5

**Java Version:** u8261

**How to reproduce:** Download forge 31.2.45 and this mod.

**Additional details:**
I get these errors on the loading screen:
![image](https://user-images.githubusercontent.com/31721920/97252246-8a433580-17d7-11eb-8a90-6ca0487944ff.png)

**Comment by xhayper** [comment]
Hi there, You are using Minecraft 1.15.2, while the version you downloaded was for 1.16.1.

**Comment by vizthex123** [comment]
Then how come Twitch said it was for 1.15.2? That's where I download all of my mods.

**Comment by xhayper** [comment]
Sorry, CurseForge probably confuse you, but you need to go to https://www.curseforge.com/minecraft/mc-mods/old-combat-system/files to download subversion, as the mainpage always redirect to 1.16.1 one.
